# pako/ubuntu1604-ssh-nginx
FROM ubuntu:16.04
MAINTAINER PK "pk@gae123.com"
ENV REFRESHED_AT 2017-05-30

RUN apt-get update
RUN apt-get -y install rsync openssh-server sudo
RUN apt-get -y install nginx

