
images:
  - name: ubuntu1404
    docker_name: pako/ubuntu1404-ssh-rsync:1.0
    extra_flags: --entrypoint /home/${USER}/projects/0.sd2/examples/entrypoint.sh

  - name: ubuntu1604
    docker_name: pako/ubuntu1604-ssh-rsync:1.0
    extra_flags: --entrypoint /home/${USER}/projects/0.sd2/examples/entrypoint.sh


hosts:
  - name: paros
    base: 1     # Used in the IP address of the containers, unique for each host
    IdentityFile: ~${USER}/.ssh/id_rsa-2015

    containers:
     - "ubuntu1404"   # paros-0
     - "ubuntu1404"   # paros-1
     - "ubuntu1604"   # paros-2
     - "ubuntu1604"   # paros-3


workspaces:
  # An abstract workspace shared by all my workspaces
  - name: any
    abstract: yes
    paths:
      - exclude:
          - '*.pyc'
          - '*.swp'
          - '*.swpx'
          - .idea
          - '.idea/**'
  # An abstract workspace for all the sd2 workspaces
  - name: sd2
    abstract: yes
    extends: any
    delete: yes
    paths:
      - exclude:
        - /out
        - /out/**
        - "/.git"     # we do version control on EH so we do not copy it over
  # An actual workspace
  - name: 0.sd2
    extends: sd2
    source_root: ${HOME}/projects/${name} # ${name} will be 0.sd2
    dest_root: /tmp/${name}
    targets:
      - paros-0
      - name: paros-2
        enabled: false
  # Another actual workspace
  - name: 1.sd2
    extends: sd2
    source_root: ${HOME}/projects/${name} # ${name} will be 1.sd2
    dest_root: /tmp/${name}
    targets:
      - paros-1
      - paros-3
