
images:
  - name: ubuntu1604
    # Execute this command before starting the container to get the entrypoint script
    run_before: >-
      wget -O ~/.tmp_entrypoint.sh 
      https://raw.githubusercontent.com/gae123/sd2/master/examples/entrypoint.sh;
      chmod +x ~/.tmp_entrypoint.sh
    docker_image_name: pako/ubuntu1604-ssh-rsync:1.2
    environ:
      - USER:$$USER
      - USER_ID:$(id -u)
      - GROUP_ID:$(id -g)
      - SD2_EP_SSH:1
      - SD2_EP_DAEMON:1
      - SD2_EP_TZ:America/Los_Angeles
    extra_flags: --entrypoint /home/$$USER/.tmp_entrypoint.sh


hosts:
  - name: paros
    IdentityFile: ~${USER}/.ssh/id_rsa-2015

    
containers:
     - name: "0"    # This will be called paros-0
       hostname: paros
       imagename: "ubuntu1604"    
       enabled: yes
     - name: "1"    # This will be called paros-1
       hostname: paros
       imagename: "ubuntu1604"    
       enabled: yes


workspaces:
  # An abstract workspace shared by all my workspaces
  - name: any
    abstract: yes
    paths:
      - exclude:
          - '*.pyc'
          - '*.swp'
          - '*.swpx'
          - .idea
          - '.idea/**'
  # An abstract workspace for all the sd2 workspaces
  - name: sd2
    abstract: yes
    extends: any
    delete: yes
    paths:
      - exclude:
        - "/out"      # The artifacts directory exists only on the DH
        - "/.git"     # we do version control on EH so we do not copy it over
  # A concrete workspace
  - name: 0.sd2
    extends: sd2
    source_root: ${HOME}/projects/${name} # ${name} will be 0.sd2
    dest_root: /tmp/${name}
    targets:
      - name: paros-0
        enabled: yes
  # Another concrete workspace
  - name: 1.sd2
    extends: sd2
    source_root: ${HOME}/projects/${name} # ${name} will be 1.sd2
    dest_root: /tmp/${name}
    targets:
      - name: paros-1
        enabled: yes
