
images:
  - name: ubuntu1604
    docker_name: pako/ubuntu1604-ssh-rsync:1.0
    extra_flags: --entrypoint /home/${USER}/projects/0.sd2/examples/entrypoint.sh
    ports:
      - 80:80

hosts:
  - name: paros
    base: 0     # The internal ip of these containers will be 172.172.0.100, 172.172.0.101 etc
    IdentityFile: ~${USER}/.ssh/id_rsa-2015

    containers:
     - ubuntu1604
     - ubuntu1604

workspaces:
  # An abstract workspace shared by all my workspaces
  - name: any
    abstract: yes
    paths:
      - exclude:
          - '*.pyc'
          - '*.swp'
          - '*.swpx'
          - .idea
          - '.idea/**'
  # An abstract workspace for all the sd2 workspaces
  - name: sd2
    abstract: yes
    extends: any
    delete: yes
    paths:
      - exclude:
        - /out
        - /out/**
  # A concrete workspace
  - name: 0.sd2
    extends: sd2
    source_root: ${HOME}/projects/${name} # ${name} will be 0.sd2
    dest_root: /tmp/${name}
    targets:
      - paros-0
  # Another concrete workspace
  - name: 1.sd2
    extends: sd2
    source_root: ${HOME}/projects/${name} # ${name} will be 1.sd2
    dest_root: /tmp/${name}
    targets:
      - paros-1
