name: sd2ui
on: [push]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build sd2ui
        working-directory: ./macos
        run: xcodebuild build
      - name: Archive sd2ui
        uses: actions/upload-artifact@v2
        with:
          name: sd2ui
          path: |
            macos/build/Release
            !macos/build/Release/*.swiftmodule
            !macos/build/Release/*.dSYM